### ISSUE TITLE
didn't do anything for my setup

### ISSUE THREAD

**Issue by mystixa** [Kleinrotti/VoukoderManager#2]
win7 ultimate.. with adobe cs6 including premier pro.. Ive just started using voukoder to see if it helps times and all that. Nothing conclusive on that, but thats why I saw this. Downloaded, installed, opened and nothing there in either tab. I have voukoder 4.1 installed and premier sees it, media encoder has finished a few encodes with it.

Looks neat if I could get it to work..

**Comment by Kleinrotti** [comment]
I think this has something to do with Windows 7 and where the registry entries of programs are located. I'm using Windows 10 so I couldn't test it on Windows 7. Seems like in Windows 7 they are stored somewhere else and VoukoderManager can't find the installed Adobe Products.
On Windows 10 it is stored here: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

Maybe you can find the path for Windows 7 @mystixa?
